name: Storybook Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [latest]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
    - run: npm run build
    - run: npx playwright install --with-deps
    - name: Build Storybook
      run: npm run build-storybook --quiet
    - name: Serve Storybook and run tests
      run: |
        npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "npx http-server storybook-static --port 6006 --silent" \
          "npx wait-on tcp:6006 && npm test -- --coverage"
    - run: npx nyc report --reporter=lcov -t .nyc_output/ --report-dir coverage
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@3b7078ee895f74fc267b7b267c88211df59fa816 # v2.2.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
