name: Storybook Tests

on: deployment_status

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'

    strategy:
      matrix:
        node-version: [lts/*, latest]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
    - run: npm run build
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Storybook tests
      run: yarn test-storybook
      env:
        TARGET_URL: '${{ github.event.deployment_status.target_url }}'
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
